{% set name = "dryhic" %}
{% set version = "0.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/jrhawley/dryhic.git

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bit64, curl, R.utils, knitr, xts, nanotime, zoo
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    # - {{posix}}filesystem        # [win]
    # - {{posix}}make
    # - {{posix}}sed               # [win]
    # - {{posix}}coreutils         # [win]
    # - {{posix}}zip               # [win]
    # - llvm-openmp                # [osx]

  host:
    - r-base
    - r-magrittr
    - r-matrix
    - r-mgcv
    - r-dplyr
    - r-data.table
    - r-rspectra
  run:
    - r-base


test:
  commands:
    - $R -e "library('dryhic')"           # [not win]
    - "\"%R%\" -e \"library('dryhic')\""  # [win]

about:
  home: http://github.com/jrhawley/dryhic
  license: GPLv3
  license_family: GPL3
  license_file: ../LICENSE
  summary: A set of tools to manipulate HiC data.

extra:
  recipe-maintainers:
    - jrhawley
